# Generated by Django 3.2.7 on 2022-05-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('vote_average', models.FloatField()),
                ('poster_path', models.CharField(max_length=100)),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField()),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
