# Generated by Django 3.2.12 on 2022-05-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
